name: Resume Automation Lab

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # force Node.js 24 now

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup environment
        run: sudo apt-get install -y pandoc texlive-xetex

      - name: Create docs folder
        run: mkdir -p docs   # ensures docs folder exists

      - name: Generate PDF
        run: pandoc src/resume.md -o docs/resume.pdf

      - name: Generate HTML
        run: pandoc src/resume.md -o docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
